# image will be published to ghcr.io/mufeedali/shinyblue
name: shinyblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
      # In my case, I copy /etc in order to add the vscode repo. But should be avoided otherwise.
      - etc: /etc # copies config/files/etc into your image's /etc immediately,
                  # for use with further modules.

  # Atuin doesn't get packaged anywhere, so pull from the bluefin-cli container.
  # This is also what Bluefin itself does.
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/bluefin-cli /usr/bin/atuin /usr/bin/atuin

  # This module will always download the latest version of a font and properly configure it.
  - type: fonts
    fonts:
      # Supports google-fonts and nerd-fonts
      nerd-fonts:
        - JetBrainsMono

  - type: rpm-ostree
    install:
      - bat
      - code # VS Code
      - eza
      - fish
      - micro # Cool terminal text editor
      - rclone
      - restic
      - ripgrep
      - rocm-hip
      - rocm-opencl
      - rsms-inter-fonts
      - sshfs
      - wl-clipboard
      - meson
    remove:
      - nvtop
      - webapp-manager
      - clapper # I use celluloid
      - gnome-shell-extension-hanabi # I hate when stuff moves too much
      - waydroid # I have a phone
      - waydroid-selinux
      - xapps # I don't use any of them
      - python3-xapps-overrides
      - cockpit-bridge
      - cockpit-navigator
      - cockpit-podman
      - cockpit-selinux
      - cockpit-storaged
      - cockpit-system

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # --- The Essentials ---
        - app.drey.Dialect # Yeah...
        - dev.mufeed.Wordbook # You know exactly what I'm doing...
        - io.missioncenter.MissionCenter # Task manager-esque app
        - org.onlyoffice.desktopeditors # OnlyOffice
        # ----- Cool Apps ------
        - io.github.celluloid_player.Celluloid # mpv-based media player
        - org.gnome.gitlab.cheywood.Buffer # Ephemeral text editor
        # ----- For Gaming -----
        - page.kramo.Cartridges # Game Launcher
        - com.heroicgameslauncher.hgl # Epic, Amazon and GOG Launcher
        - com.usebottles.bottles # Wine UI
        - com.github.mtkennerly.ludusavi # Save file backup tool
        - io.itch.itch # Itch Launcher
        # ----- Emulators ----
        - info.cemu.Cemu # Wii U
        - app.xemu.xemu # XBox
        - net.kuribo64.melonDS # DS
        - net.pcsx2.PCSX2 # PS2
        - net.rpcs3.RPCS3 # PS3
        - org.DolphinEmu.dolphin-emu # Wii/GameCube
        - org.ppsspp.PPSSPP # PSP
        - org.ryujinx.Ryujinx # Switch
        # ----- Development ----
        - ca.desrt.dconf-editor
        - org.flatpak.Builder # Required for VS Code flatpak extension among others
        - com.github.tchx84.Flatseal # Flatpak Permissions Manager
        # ----- Desktop -----
        - com.mattjakeman.ExtensionManager
        - it.mijorus.gearlever
      remove:
        - io.github.dvlv.boxbuddyrs

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

