# image will be published to ghcr.io/mufeedali/shinyblue
name: shinyblue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
      # In my case, I copy /etc in order to add the vscode repo. But should be avoided otherwise.
      - etc: /etc # copies config/files/etc into your image's /etc immediately,
                  # for use with further modules.

  # Atuin doesn't get packaged anywhere, so pull from the bluefin-cli container.
  # This is also what Bluefin itself does.
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/bluefin-cli /usr/bin/atuin /usr/bin/atuin

  # This module will always download the latest version of a font and properly configure it.
  - type: fonts
    fonts:
      # Supports google-fonts and nerd-fonts
      nerd-fonts:
        - JetBrainsMono

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
    install:
      - bat
      - code
      - eza
      - fish
      - micro
      - ptyxis
      - rclone
      - restic
      - ripgrep
      - rocm-hip
      - rocm-opencl
      - rsms-inter-fonts
      - sshfs
      # -- Ptyxis overrides --
      - vte291
      - vte-profile
      # ----------------------
      - wl-clipboard
    remove:
      - htop
      - nvtop
      # -- Ptyxis overrides --
      - vte291
      - vte-profile
      # ----------------------

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - app.drey.Dialect # Yeah...
        - dev.mufeed.Wordbook # You know exactly what I'm doing...

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

